"""empty message

Revision ID: 12c743b12ed4
Revises: 65d3979a4bea
Create Date: 2017-10-19 00:11:11.997399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c743b12ed4'
down_revision = '65d3979a4bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='categorys')
    op.create_foreign_key(None, 'categorys', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'categorys', ['category_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'posts', ['post_id'], ['id'])
    op.drop_index('name', table_name='tags')
    op.create_foreign_key(None, 'tags', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_index('name', 'tags', ['name'], unique=True)
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'categorys', type_='foreignkey')
    op.create_index('name', 'categorys', ['name'], unique=True)
    # ### end Alembic commands ###
