"""post view count

Revision ID: 4d6bdfb91f62
Revises: 12c743b12ed4
Create Date: 2017-10-19 23:17:14.396641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6bdfb91f62'
down_revision = '12c743b12ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'categorys', 'users', ['author_id'], ['id'])
    op.add_column('posts', sa.Column('viewcount', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'categorys', ['category_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'viewcount')
    op.drop_constraint(None, 'categorys', type_='foreignkey')
    # ### end Alembic commands ###
