"""empty message

Revision ID: 55b7ad5d8067
Revises: 99fe9eefab02
Create Date: 2017-10-10 23:37:30.710316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55b7ad5d8067'
down_revision = '99fe9eefab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('fragment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_posts_create_time'), 'posts', ['create_time'], unique=False)
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'timestamp')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('posts', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_posts_create_time'), table_name='posts')
    op.drop_column('posts', 'fragment')
    op.drop_column('posts', 'create_time')
    # ### end Alembic commands ###
