"""initial migration

Revision ID: 7069a67d62ab
Revises: b5430094bfa7
Create Date: 2017-07-25 10:55:51.070130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7069a67d62ab'
down_revision = 'b5430094bfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name1', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'roles', ['name1'])
    op.add_column('users', sa.Column('username1', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_username1'), 'users', ['username1'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username1'), table_name='users')
    op.drop_column('users', 'username1')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'name1')
    # ### end Alembic commands ###
