"""modify posts title

Revision ID: 7eb46de45247
Revises: be3c0596ed0a
Create Date: 2017-09-24 04:54:31.930413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7eb46de45247'
down_revision = 'be3c0596ed0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='posts')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'body_html')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('posts', sa.Column('body_html', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index('title', 'posts', ['title'], unique=True)
    # ### end Alembic commands ###
