"""empty message

Revision ID: 8e765c39cd01
Revises: 7eb46de45247
Create Date: 2017-10-07 03:29:10.285633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e765c39cd01'
down_revision = '7eb46de45247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'real_avatar')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
